# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT
name: Setup Kani Dependencies (Ubuntu 18)
runs:
  using: composite
  steps:
    - name: Free up docker disk space
      shell: bash
      run: |
        # inspired by https://github.com/easimon/maximize-build-space/blob/master/action.yml
        df -h
        rm -r /mnt/host-local/lib/android /mnt/host-local/.ghcup
        df -h

    - name: Install system dependencies
      shell: bash
      run: |
        apt-get update
        apt-get install -y software-properties-common apt-utils
        apt-get update
        apt-get install -y \
          build-essential bash-completion curl lsb-release sudo g++ gcc flex \
          bison make patch git
