[package]
name = "rustc_smir"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[package.metadata.rust-analyzer]
# This package uses rustc crates.
rustc_private=true
